spring:
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/msg_gateway?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: ENC#ZIZ0vdjV6HBQEGKi3FNIy9gYfs4GvaGBxHYj8MZfkC0ZtSFdGOUmgBOAT8y6uHYD
    password: ENC#ktHZOyAxa09PASaXGnaWhEbn9VPaz8hs2T8TAHTZrHKn6HE1nxaxzlLhREqS3bvm
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
  application:
    name: msg-gateway
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  security:
    enabled: false
    user:
      name: ENC#AeYXP81qEjiOJOYh1eIJE/cz52owOCVqubBkLdBFVZutGJBl8+YPjfgfI9gHtvBy
      password: ENC#qC2k83W3O6otgxFfo3/n0N8bMgOXuZkDoLiCKcnmLnKVzRRuJlj95aZu7yARSYiJ
mybatis:
  base-packages: com.tuituidan.openhub.mapper
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tuituidan.openhub.bean.entity
server:
  port: 8084

dictionary:
  # 数据字典类型，xlsx-从excel中获取，database-从数据库中获取，需要配置查询sql，remote-远程获取，需要配置url
  type: xlsx

thread-pool:
  core-pool-num: 2
  max-pool-num: 2
  thread-name-prefix: msg-gateway
  ext-pool:
    data-analyse:
      queue-size: 2000
      thread-name-prefix: receive-pool
    data-push:
      queue-size: 2000
      thread-name-prefix: push-pool
